Conflux-Chain/conflux-documentation

src/pages/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-documentation/1)
=> comment link

.github/workflows/deploy.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-documentation/2)
=> Test action

blog/2019-05-28-first-blog-post.md
Test PR
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-documentation/7)
=> Test Commit

docs/learn/conflux-basics/accounts.md
"Accounts" page added and completed. Pending review for merging branches. @Pana
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-documentation/10)
=> Added 'Accounts' Page

docs/learn/conflux-basics/spaces.md
Added 'Spaces' Page on Conflux Basics Section
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-documentation/11)
=> Added 'Spaces' Page

docs/contribute/_category_.json, docs/get-involved/_category_.json, docs/smart-contracts/_category_.json, docs/smart-contracts/introduction-to-smart-contracts.md, docs/tutorial-basics/_category_.json, docs/tutorial-extras/_category_.json
This PR
- creates new section: `Smart Contracts`
- adds content to smart contracts sections: `Introduction to Smart Contracts`
- reorgs index of sections
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-documentation/13)
=> Introduction to Smart Contracts

docs/build/conflux-espace/_category_.json, docs/build/conflux-espace/evm-compatibility.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-documentation/14)
=> Added EVM Compatibility Page

docusaurus.config.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-documentation/26)
=> Changed docusaurus config file

docs/learn/conflux-basics/additional-resources/_category_.json, docs/learn/conflux-basics/additional-resources/papers.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-documentation/37)
=> Added Papers Page

docs/build/conflux-core/_category_.json, docs/build/conflux-core/tools/_category_.json, docs/build/conflux-core/tools/tools.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-documentation/36)
=> Added Tools Page

docs/learn/conflux-basics/transactions/_category_.json, docs/learn/conflux-basics/transactions/my-first-transaction.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-documentation/34)
=> Added My First Transaction Page

docs/learn/tutorials/_category_.json, docs/learn/tutorials/ledger-on-core.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-documentation/29)
=> Ledger on core

docs/learn/conflux-basics/transactions/_category_.json, docs/learn/conflux-basics/transactions/why-transaction-is-pending.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-documentation/40)
=> Added Why Transaction is Pending Page

docs/learn/getting-started/_category_.json, docs/learn/tutorials/ledger.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-documentation/16)
=> Added Ledger Tutorial

docs/mine/running-a-light-node.md
- adds `Running a Light Node` in the `mine` section
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-documentation/18)
=> Running a Light Node

docs/learn/conflux-basics/transactions/_category_.json, docs/learn/conflux-basics/transactions/transaction-stage.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-documentation/32)
=> Added Transaction Stages Page

docs/learn/tutorials/_category_.json, docs/learn/tutorials/metamask.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-documentation/17)
=> Added text content. Images are still pending

docs/learn/getting-started/network-endpoints/_category_.json, docs/learn/getting-started/network-endpoints/core-endpoints.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-documentation/30)
=> Added Core Endpoints Page

docs/mine/running-a-full-node/_category_.json, docs/mine/running-a-full-node/configuration-file/configuration-file.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-documentation/35)
=> Added Configuration File Page

docs/espace/build/_category_.json, docs/espace/build/cross-space-call.md, docs/espace/build/espace-addresses.md, docs/espace/build/evm-compatibility.md, docs/espace/build/grants/_category_.json, docs/espace/build/grants/growth-grants.md, docs/espace/build/grants/incubation-program.md, docs/espace/build/grants/technical-grants.md, docs/espace/build/resources/_category_.json, docs/espace/build/resources/additional-documentation.md, docs/espace/build/resources/developer-tools.md, docs/espace/build/resources/infrastructure.md, docs/espace/build/resources/json-rpc.md, docs/espace/learn/_category_.json, docs/espace/learn/accounts.md, docs/espace/learn/espace-guide.md, docs/espace/learn/network-endpoints.md, docs/espace/learn/overview.md, docs/espace/learn/tutorials/_category_.json, docs/espace/learn/tutorials/transfer-funds-across-chains.md, docs/espace/learn/tutorials/transfer-funds-across-spaces.md, docs/espace/learn/tutorials/using-ledger.md, docs/espace/learn/tutorials/using-metamask.md, docs/espace/learn/why-pos.md, docs/general/conflux-basics/accounts.md
Added all folders and placeholders to eSpace Section
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/51)
=> Added folders and placeholders to eSpace Section

docs/espace/build/cross-space-call.md, docs/espace/build/evm-compatibility.md, docs/espace/learn/tutorials/using-metamask.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/52)
=> Copy pages to espace

docs/core/learn/core-space-basics/transactions/common-errors.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/62)
=> Added Common Error Page

docs/general/run-a-node/running-independent-chain.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/64)
=> Added Run an Independent Chain Page

docs/general/run-a-node/compiling-conflux-client.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/66)
=> Added Compiling the Conflux Client Page

docs/general/run-a-node/downloading-conflux-client.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/67)
=> Added Downloading the Conflux Client Page

docs/espace/learn/overview.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/68)
=> Added eSpace Introduction Page

docs/espace/learn/espace-guide.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/63)
=> Added eSpace Guide Page

docs/espace/learn/why-pos.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/73)
=> Remove why-pos in espace

docs/general/faq/faq.md
A new FAQ section is created to integrate FAQs in other articles. This would make it easier for users to check the answers of FAQs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/57)
=> Create a new FAQ section

docs/core/learn/core-space-basics/transactions/what-is-transaction.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/56)
=> Polish core space transaction article. #44

docs/espace/build/network-endpoints.md, docs/espace/learn/network-endpoints.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/82)
=> Added Network Endpoints Page + Fixed Location

docs/general/run-a-node/running-full-node.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/81)
=> Added Running a Full Node Page

docs/espace/_category_.json, docs/espace/build/_category_.json, docs/espace/build/grants/_category_.json, docs/espace/build/resources/_category_.json, docs/espace/learn/_category_.json, docs/espace/learn/tutorials/_category_.json, docusaurus.config.js, package.json, yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/80)
=> Added eSpace Descriptions

docs/core/build/send-transactions-using-SDK.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/86)
=> Add send-transactions-using-SDK page

docs/espace/build/resources/json-rpc.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/89)
=> Added JSON-RPC Page

docs/general/conflux-basics/consensus-mechanisms/proof-of-work/ghast.md, yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/87)
=> Added GHAST Page

docs/general/conflux-basics/consensus-mechanisms/proof-of-work/_category_.json, docs/general/conflux-basics/consensus-mechanisms/proof-of-work/proof-of-work-overview.md, docs/general/conflux-basics/consensus-mechanisms/proof-of-work/proof-of-work.mdx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/90)
=> pow overview

docs/general/mine-stake/mine/running-mining-node.md, docs/general/run-a-node/node-requirements.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/91)
=> Added Node Requirements + Running a Mining Node

docs/general/mine-stake/stake/run-pos-node.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/94)
=> Added Run a PoS Node Page

docs/core/learn/core-space-basics/accounts.md, docs/espace/learn/accounts.md, docs/general/conflux-basics/accounts.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/95)
=> Espace address and improvements for account pages

docs/general/conflux-basics/conflux-governance/governance-overview.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/101)
=> Added Governance Overview Page

docs/general/conflux-basics/economics.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/97)
=> Updated Economics Page

docs/core/learn/core-space-basics/addresses.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/104)
=> Update core address

docs/general/mine-stake/stake/staking-considerations.md, docs/general/mine-stake/stake/staking-risks.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/105)
=> Added Staking Risks Page

docs/core/learn/getting-started/what-to-do-next.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/112)
=> Finish what-to-do-next

src/css/custom.css
This commit fix the page font style but would disturb home page foot text style
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/111)
=> style: initial font style revert

docs/core/build/json-rpc/pub-sub.md, docs/general/run-a-node/cli.md, docs/general/run-a-node/configuration-files.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/114)
=> Add api pages

docs/general/conflux-basics/glossary.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/116)
=> Add internal-transactions to glossary

docs/core/build/grants.md, docs/core/build/token-standards.md, docs/espace/build/grants/growth-grants.md, docs/espace/build/grants/incubation-program.md, docs/espace/build/grants/technical-grants.md, docs/espace/build/resources/additional-documentation.md, docs/espace/build/resources/developer-tools.md, docs/espace/build/resources/infrastructure.md, docs/general/run-a-node/running-archive-node.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/124)
=> Pages with in-progress template

docs/espace/build/cross-space-call.md, docs/espace/build/resources/additional-documentation.md, docs/espace/build/resources/graph/_category_.json, docs/espace/build/resources/graph/create-subgraphs.md, docs/espace/build/resources/graph/setup-graph-node.md, docs/espace/build/resources/json-rpc.md, docs/espace/espace.mdx, docs/espace/learn/tutorials/using-metamask.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/135)
=> Added The Graph  Pages

docusaurus.config.js, package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/136)
=> Update edit URL

.github/ISSUE_TEMPLATE/bug_report_typo.md, .github/ISSUE_TEMPLATE/feature_request_improvement.md, README.md, docs/general/CONTRIBUTING.md, docs/general/build/build.mdx, docs/general/faq/faq.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/137)
=> Create contributing guide

docs/general/faq/core-space-transactions/why-transaction-is-pending.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/165)
=> fix wrong errata file

docs/core/build/fluent.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/167)
=> Add fluent wallet integration

docs/general/build/_category_.json, docs/general/build/build.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/173)
=> fix wrong description of general/build

docs/core/build/sdks-and-tools/core-endpoints.md, docs/espace/build/network-endpoints.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/177)
=> Add confura ratelimit spec

docs/general/build/nfts/pinata.md, docusaurus.config.js, package.json, yarn.lock
Fixed some details in the pinata page.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/176)
=> Pinata-fixes

.github/workflows/deploy.yaml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/180)
=> Bot update action

docs/core/build/sdks-and-tools/core-endpoints.md, docs/espace/build/network-endpoints.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/182)
=> add confura websocket endpoint

docs/general/build/tools/_category_.json, docs/general/build/tools/use-wallet.md
I added use-wallet page on General/Build/Tools
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/183)
=> Added use-wallet page

docs/general/conflux-basics/wallets.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/192)
=> fix-broken-link

docs/core/build/sdks-and-tools/core-endpoints.md, docs/espace/build/network-endpoints.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/196)
=> Add standard fee tier buy links

docs/core/build/json-rpc/cfx-namespace.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/206)
=> Update cfx-namespace json-rpc doc

docs/core/learn/core-space-basics/internal-contracts/sponsor-whitelist-control.md, docs/core/learn/core-space-basics/storage.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/213)
=> fix: storage points usage priority

.github/workflows/test-l10n_deploy.yaml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/215)
=> ci: l10n deployment test

docs/general/build/tools/web3paywall.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/217)
=> add paywall url to tutorial page

docs/core/build/json-rpc/cfx-namespace.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/219)
=> Add explanation to cfx_getAdmin RPC when input parameter is user address

docusaurus.config.js, package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/225)
=> l10n: spanish support

docusaurus.config.js
- [ X] I have read the [Contributing Guidelines on pull requests](https://doc.confluxnetwork.org/docs/general/CONTRIBUTING#create-a-pull-request).
- [ X] **This is NOT a PR to submit translation**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/229)
=> Added search feature

docs/general/faq/community-faqs.md, docs/general/faq/core-space-transactions/_category_.json, docs/general/faq/nodes-faqs.md
- [X ] I have read the [Contributing Guidelines on pull requests](https://doc.confluxnetwork.org/docs/general/CONTRIBUTING#create-a-pull-request).
- [X ] **This is NOT a PR to submit translation**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/231)
=> Added FAQs pages

docs/core/core.mdx, docs/espace/espace.mdx, docs/general/general.mdx, docs/index.md, docusaurus.config.js
- [ x] I have read the [Contributing Guidelines on pull requests](https://doc.confluxnetwork.org/docs/general/CONTRIBUTING#create-a-pull-request).
- [x ] **This is NOT a PR to submit translation**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/230)
=> Added Index Page

docs/general/general.mdx, docs/general/overview.md, docs/index.md, docusaurus.config.js
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/236)
=> fix: overview page links

docs/core/build/json-rpc/cfx-namespace.md, docs/core/build/json-rpc/pos-namespace.md, docs/core/build/json-rpc/trace-namespace.md, docs/core/core.mdx, docs/core/learn/core-space-basics/internal-contracts/params-control.md, docusaurus.config.js
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/249)
=> update label and RPC doc

docs/espace/DeveloperQuickstart.md, docs/espace/FAQs.md, docs/espace/Overview.md, docs/espace/UserGuide.md, docs/espace/build/accounts.md, docs/espace/build/cross-space-bridge.md, docs/espace/build/deployed-contracts.md, docs/espace/build/evm-compatibility.md, docs/espace/build/jsonrpc-compatibility.md, docs/espace/network-endpoints.md, docs/espace/tutorials/VerifyContracts.md, docs/espace/tutorials/deployContract/hardhatAndFoundry.md, docs/espace/tutorials/deployContract/remix.md, docs/espace/tutorials/deployContract/thirdweb.md, docs/espace/tutorials/tutorials.mdx, docusaurus.config.js, src/components/Card/index.js, src/modules/docCatalog/index.js, src/modules/featureCards/index.js, src/pages/index.js, src/pages/index.module.css
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/264)
=> update home page of doc site

scripts/checkGitCommitBash.sh
#269
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/270)
=> Create checkGitCommitBash.sh 

vercel.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/273)
=> Employ vercel auto job cancelation

.github/workflows/test-l10n_deploy.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/281)
=> ci: add reopen pr trigger for l10n_main

docs/espace/network-endpoints.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/280)
=> fix: typo for us east rpc ws endpoint

docs/core/FAQs.md, docs/core/core-space-basics/Intro.md, docs/core/core-space-basics/accounts.md, docs/core/core-space-basics/addresses.md, docs/core/core-space-basics/core-transactions.md, docs/core/tutorials/how-to-sponsor-contract.md, docs/espace/FAQs.md, docs/espace/tutorials/VerifyContracts.md, docs/general/conflux-basics/accounts.md, docs/general/conflux-basics/glossary.md, docs/overview/overview.mdx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/296)
=> Fix broken links, and small optimzation

docs/espace/build/infrastructure/graph/graph.mdx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/310)
=> add `Congraph` usage note

docs/general/build/grants.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/318)
=> Added the "Grants" page

docs/espace/network-endpoints.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/321)
=> add md suffix to paywall link

docs/general/CONTRIBUTING.md, docs/overview/overview.mdx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/319)
=> Add grants link in contributing page

docs/general/tutorials/transferring-funds/across-chains/zero-gravity.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/329)
=> Add Zero Gravity FAQ

docs/core/build/index.json, docs/core/core-endpoints.md, docs/core/core-space-basics/_category_.yml, docs/core/tutorials/_category_.yml, docs/espace/Overview.md, docs/general/mine-stake/stake/faqs.md, docs/general/run-a-node/Overview.md, docs/general/run-a-node/TroubleShooting.md, docs/general/run-a-node/advanced-topics/_category_.json, docs/general/run-a-node/advanced-topics/compiling-conflux-client.md, docs/general/run-a-node/how-to-upgrad.md, docs/general/run-a-node/node-types.md, docs/general/run-a-node/nodes-faqs.md, docs/general/run-a-node/run-a-node.md, docs/general/run-a-node/snapshot-tool.md, docs/overview/overview.mdx, docusaurus.config.js, src/modules/docCatalog/index.js
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/334)
=> add how to upgrade node

docs/general/run-a-node/snapshot-tool.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/336)
=> Fix snapshot unzip command

docs/general/faq/faq-index.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/343)
=> Created FAQs Index page

docs/general/run-a-node/advanced-topics/compiling-conflux-client.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/344)
=> Add more detail for node binary compiling

docs/general/build/tools/web3paywall.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/346)
=> Add how to use api key in paywall documents

.github/workflows/deploy.yaml, .github/workflows/test-l10n_deploy.yaml, docs/espace/build/infrastructure/RPC-Provider.md, docs/espace/network-endpoints.md, docs/espace/tutorials/VerifyContracts.md, docs/general/faq/community-faqs.md, docs/general/faq/core-space-transactions/core-transaction-faqs.md, docs/general/hardforks/v2.0.md, docs/general/run-a-node/Overview.md, docs/general/run-a-node/TroubleShooting.md, docusaurus.config.js, i18n/ar/docusaurus-plugin-content-docs/current/espace/tutorials/VerifyContracts.md, i18n/ar/docusaurus-plugin-content-docs/current/general/run-a-node/Overview.md, i18n/es/docusaurus-plugin-content-docs/current/espace/network-endpoints.md, i18n/es/docusaurus-plugin-content-docs/current/espace/tutorials/VerifyContracts.md, i18n/es/docusaurus-plugin-content-docs/current/general/faq/community-faqs.md, i18n/es/docusaurus-plugin-content-docs/current/general/faq/core-space-transactions/core-transaction-faqs.md, i18n/es/docusaurus-plugin-content-docs/current/general/hardforks/v2.0.md, i18n/es/docusaurus-plugin-content-docs/current/general/run-a-node/Overview.md, i18n/es/docusaurus-plugin-content-docs/current/general/run-a-node/TroubleShooting.md, i18n/zh/docusaurus-plugin-content-docs/current/core/core-space-basics/core-transactions.md, i18n/zh/docusaurus-plugin-content-docs/current/espace/network-endpoints.md, i18n/zh/docusaurus-plugin-content-docs/current/espace/tutorials/VerifyContracts.md, i18n/zh/docusaurus-plugin-content-docs/current/general/faq/community-faqs.md, i18n/zh/docusaurus-plugin-content-docs/current/general/faq/core-space-transactions/core-transaction-faqs.md, i18n/zh/docusaurus-plugin-content-docs/current/general/hardforks/v2.0.md, i18n/zh/docusaurus-plugin-content-docs/current/general/run-a-node/Overview.md, i18n/zh/docusaurus-plugin-content-docs/current/general/run-a-node/TroubleShooting.md, package.json, yarn.lock
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/342)
=> refactor: v3 migration

docs/espace/build/run-a-node.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/356)
=> fix: title typo

docusaurus.config.js
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/358)
=> Update docusaurus.config.js to detect broken links. Ref #357

docs/core/core-space-basics/Intro.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/363)
=> Improve Core Space Intro writing

docusaurus.config.js, static/js/clarity.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/366)
=> Add microsoft clarity

docs/general/run-a-node/run-a-node.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/387)
=> fix: running the binary directly doesn't require dependencies

docs/espace/build/evm-compatibility.md, docs/general/run-a-node/node-types.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/388)
=> fix: improper 'w' usage

docs/general/conflux-basics/ecosystem.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/392)
=> Added Ecosystem Page + Video

docs/general/build/smart-contracts/solidity-basics.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/421)
=> fix: crowdin i18n error

docs/core/build/json-rpc/cfx-namespace.md, docs/core/build/json-rpc/rpc-behaviour/_category_.yml, docs/core/build/json-rpc/rpc-behaviour/cfx_estimateGasAndCollateral-behaviour.md, docs/core/build/json-rpc/rpc-behaviour/cfx_sendTransaction-errors.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/420)
=> add cfx_call & cfx_estimateGasAndCollateral errors

docs/espace/DeveloperQuickstart.md, docs/espace/tutorials/scaffoldCfx/scaffold.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/433)
=> Add scaffold-eth-2 in eSpace developer quickstart

docs/general/run-a-node/advanced-topics/downloading-conflux-client.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/434)
=> Updating regarding the issue #430

.github/ISSUE_TEMPLATE/bug_report_typo.yml, .github/ISSUE_TEMPLATE/feature_request_improvement.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/437)
=> add 'dework' as default issue label

.github/ISSUE_TEMPLATE/bug_report_typo.yml, .github/ISSUE_TEMPLATE/feature_request_improvement.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/438)
=> Add dework label

docs/core/getting-started/what-to-do-next.md, docs/espace/tutorials/deployContract/hardhatAndFoundry.md, docs/general/tutorials/wallets/ledger.md, docs/overview/overview.mdx, docs/templates/links.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/445)
=> fix: broken discord links

docs/core/build/fluent.md, docs/core/core-developer-quickstart.md, docs/overview/for-dapp-developers.mdx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/436)
=> Frontend Overview for dApp Developers

docs/general/build/smart-contracts/gas-optimization/constant.md, docs/general/conflux-basics/glossary.md
Added definitions: Mined, Finalization, Pivot Chain, EVM
This PR aims to solve the following issues:
https://github.com/Conflux-Chain/conflux-documentation/issues/469
https://github.com/Conflux-Chain/conflux-documentation/issues/371
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/471)
=> Added more definitions to glossary

docs/general/conflux-basics/ecosystem.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/461)
=> Fixed issue#459 -- Fix typo from ConfluxHub description

docs/general/conflux-basics/wallets.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/462)
=> Fixed issue#460 -- Fix Fluent description from 'Choosing a wallet'

docs/general/build/smart-contracts/gas-optimization/constant.md, docs/general/build/smart-contracts/gas-optimization/error.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/478)
=> Refs #454 -- Added Error to general/build/smart-contracts/gas-optimization

docs/general/tutorials/wallets/wallets.mdx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/463)
=> Fixed issue#458, Add OKX wallet and OneKey wallet in 'Supported Wallets'

docs/general/build/smart-contracts/gas-optimization/constant.md, src/modules/docCatalog/index.js, src/modules/featureCards/index.js, src/pages/index.js
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/467)
=> Fixed issue#464 -- Fix margin issue displayed on mobile devices

docs/general/build/smart-contracts/gas-optimization/unchecked.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/468)
=> Refs #454  -- Added Unchecked to general/build/smart-contracts/gas-optimization

docs/general/build/smart-contracts/gas-optimization/clone.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/496)
=> Refs #454 -- Added Clone to general/build/smart-contracts/gas-optimization 

docs/general/build/smart-contracts/gas-optimization/reentrancy-guard.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/495)
=> Refs #454 -- Added  Low-Cost ReentrancyGuard to general/build/smart-contracts/gas-optimization 

docs/overview/for-dapp-developers.mdx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/498)
=> fix for-dapp-developers.mdx use-wallet lnk

package.json, src/theme/SearchBar.js, yarn.lock
Integration coordinated with @n1c0_dev and team. 
Demo here:
https://docsbot-demo-git-conflux-cookbookdev.vercel.app/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/500)
=> Feat add Ask Cookbook

docs/general/build/smart-contracts/contract-security/selector-collisiion.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/497)
=> Refs #474 -- Added SelectorCollision to general/build/smart-contracts/contract-security 

.github/ISSUE_TEMPLATE/bug_report_typo.yml, .github/ISSUE_TEMPLATE/feature_request_improvement.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/502)
=> remove dework from issue template

docusaurus.config.js
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/512)
=> Updated Discord Link + Removed dework Link

docs/general/run-a-node/advanced-topics/running-independent-chain.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/515)
=> chore: remove repetitive word

docusaurus.config.js
As cookbook dev is introduced, I think Algolia can be removed
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/518)
=> Remove Algolia

docusaurus.config.js, package.json, vercel.json, yarn.lock
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/523)
=> fix: default remove trailing slash

docs/general/hardforks/v2.3.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/524)
=> Fix i18n frontmatter

docs/general/build/smart-contracts/gas-optimization/increment.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/527)
=> Refs #454 -- Added Increment to general/build/smart-contracts/gas-optimization 

docs/general/build/smart-contracts/contract-security/overflow.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/528)
=> Refs #474 -- Added Overflow to general/build/smart-contracts/contract-security 

docs/general/build/smart-contracts/gas-optimization/methodIdSort.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/529)
=> Refs #454 -- Added MethodIdSort to general/build/smart-contracts/gas-optimization 

docs/general/build/smart-contracts/contract-security/signature-replay.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/530)
=> Refs #474 -- Added SignatureReplay to general/build/smart-contracts/contract-security 

docs/overview/overview.mdx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/538)
=> Small Fix on Overview Page, CONTRIBUTING link.

docs/general/build/smart-contracts/contract-security/signature-replay.md, docs/general/build/smart-contracts/gas-optimization/deleteVar.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/535)
=> Refs #454 -- Added ResetVariable to general/build/smart-contracts/gas-optimization 

docs/general/build/smart-contracts/contract-security/bypass-contract-check.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/537)
=> Refs #474 -- Added ContractCheck to general/build/smart-contracts/contract-security 

docs/core/build/json-rpc/cfx-namespace.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/539)
=> fix: example command for cfx_newFilter

docs/general/build/smart-contracts/contract-security/bad-randomness.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/545)
=> Refs #474 -- Added BadRandomness to general/build/smart-contracts/contract-security

docs/general/build/smart-contracts/contract-security/dos-attack.md, docs/general/build/smart-contracts/gas-optimization/methodIdSort.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/544)
=> Refs #474 -- Added DosAttacks to general/build/smart-contracts/contract-security

docs/general/build/smart-contracts/gas-optimization/methodIdSort.md, docs/general/build/smart-contracts/gas-optimization/payable-constructor.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/546)
=> Refs #454 -- Added EfficientConstructor to general/build/smart-contracts/gas-optimization

docs/general/build/smart-contracts/gas-optimization/bytes32String.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/548)
=> Refs #454 -- Added Bytes32String to general/build/smart-contracts/gas-optimization 

docs/general/build/smart-contracts/contract-security/tx-origin.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/549)
=> Refs #474 -- Added TxOrigin to general/build/smart-contracts/contract-security

docs/general/build/smart-contracts/contract-security/unchecked-call.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/558)
=> Refs #474 -- Added unchecked-calls to general/build/smart-contracts/contract-security

docs/espace/build/evm-compatibility.md, docs/espace/build/jsonrpc-compatibility.md, docs/espace/build/sdks/_category_.json, docs/espace/build/sdks/ethersjs.md, docs/espace/build/sdks/overview.md, docs/espace/build/sdks/web3js.md, docs/espace/build/sdks/web3py.md
Added the espace/build/sdks section + Overview Page + web3.js Guide + web3.py Guide + Embedded Video Contents
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/556)
=> Added Web3 SDKs Content

docs/general/build/smart-contracts/gas-optimization/mappingAndArray.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/562)
=> Refs #454 -- Added mappingAndArray to general/build/smart-contracts/gas-optimization

docs/core/tutorials/hardhat-conflux-plugin.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/564)
=> Fixed #551 -- Fix the error in the contract deployment code

docs/core/build/json-rpc/cfx-namespace.md, i18n/ar/docusaurus-plugin-content-docs/current/core/build/json-rpc/cfx-namespace.md, i18n/es/docusaurus-plugin-content-docs/current/core/build/json-rpc/cfx-namespace.md, i18n/ja/docusaurus-plugin-content-docs/current/core/build/json-rpc/cfx-namespace.md
- [x ] I have read the [Contributing Guidelines on pull requests](https://doc.confluxnetwork.org/docs/general/CONTRIBUTING#create-a-pull-request).
- [ x] **This is NOT a PR to submit translation**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/571)
=> docs: fix skiped to skipped

docs/general/conflux-basics/glossary.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/569)
=> Refs #566 -- Added the definition of TWAP to the glossary

docs/general/build/smart-contracts/contract-security/oracle-manipulation.md, docs/general/build/smart-contracts/contract-security/price-manipulation.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/565)
=> Refs #474 -- Added  PriceManipulation to general/build/smart-contracts/contract-security

docs/general/build/smart-contracts/contract-security/input-validation.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/575)
=> Refs #474 -- Added Improper Input Validation to Contract Security

docs/general/build/smart-contracts/gas-optimization/packing.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/580)
=> Refs #577 -- Added content on struct packing to general/build/smart-contracts/gas-optimization/packing

docs/general/CONTRIBUTING/reward-guidelines.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/579)
=> Providing rewards guideline for long term (minor) changes

docs/general/build/tools/use-wallet.md, docs/overview/for-dapp-developers.mdx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/585)
=> Add use-wallet sample projects

docs/general/build/smart-contracts/gas-optimization/non-zero-balances.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/587)
=> Refs #454 -- Added Non-Zero Balances to general/build/smart-contracts/gas-optimization 

docs/general/build/smart-contracts/contract-security/excessive-restriction.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/589)
=> Refs #474 -- Added Excessive Function Restrictions to Contract Security

docs/core/build/json-rpc/cfx-namespace.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/595)
=> fix: cfx_getCode return value

docs/general/run-a-node/snapshot-tool.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/598)
=> Update snapshot tool

docs/espace/build/infrastructure/RPC-Provider.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/607)
=> add blockpi rpc service provider

docs/espace/DeveloperQuickstart.md, docs/espace/build/evm-compatibility.md, docs/espace/build/jsonrpc-compatibility.md, docs/espace/build/transaction.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/608)
=> v2.4 update for eSpace

docs/general/build/smart-contracts/contract-security/downcasting.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/603)
=> Refs #474 -- Added Safe Downcasting to Contract Security 

docs/core/build/json-rpc/cfx-namespace.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/610)
=> core space v2.4 rpc change

docs/general/build/smart-contracts/gas-optimization/modifierAndInternal.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/601)
=> Refs #454 -- Added modifierAndInternal to general/build/smart-contracts/gas-optimization 

docs/general/hardforks/v2.4.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/612)
=> v2.4 general upgrade page

docs/core/build/json-rpc/pos-namespace.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/615)
=> Update pos lock and unlock period

docs/general/run-a-node/advanced-topics/compiling-conflux-client.md, docs/templates/parameters.ts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/624)
=> Update conflux build from source document

docs/general/conflux-basics/glossary.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/631)
=> Refs #628 -- Add the definition of faucet to the glossary 

docs/general/build/tools/web3paywall.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/639)
=> Explain api key for *.mainrpc.org rpc endpoints

docs/general/hardforks/v2.4.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/640)
=> v2.4 mainnet release

docs/general/run-a-node/advanced-topics/node-configuration.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/642)
=> RPC related configuration update

docs/general/run-a-node/advanced-topics/configuration-files.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/646)
=> chore: add configurations

docs/espace/build/cross-space-bridge.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/648)
=> fix: wrong js code example #645

docs/espace/build/jsonrpc-compatibility.md
…lity improve
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/650)
=> Remove jsonrpc-compatibility.md sendRawTx error part due to compatibility improve

docs/general/conflux-basics/glossary.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/657)
=> Refs #655 -- Add the defination of Bytecode to the glossary

docusaurus.config.js, i18n/en/code.json, i18n/en/docusaurus-theme-classic/footer.json, i18n/en/docusaurus-theme-classic/navbar.json, i18n/zh/code.json, i18n/zh/docusaurus-theme-classic/footer.json, i18n/zh/docusaurus-theme-classic/navbar.json, src/components/Card/index.js, src/components/HomeQuickStartBanner/index.tsx, src/components/ResourcesCards/index.tsx, src/modules/docCatalog/index.js, src/modules/featureCards/index.js, src/pages/index.js
resolve #375
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/660)
=> feat: add i18n to js and tsx files

docs/general/conflux-basics/glossary.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/670)
=> Refs #665 -- Add the defination of DeFi to the glossary 

docs/general/build/smart-contracts/contract-security/msg-value-in-loop.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/669)
=> Refs #474 -- Add `msg.value` in Loops to Contract Security 

docs/general/conflux-basics/glossary.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/677)
=> Add definition of Digital Signature to glossary

docs/general/build/smart-contracts/contract-security/unchecked-call.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/671)
=> Refs #666 -- Add .call() method example in Unchecked Low-Level Calls

docs/general/run-a-node/advanced-topics/configuration-files.md, i18n/zh/docusaurus-plugin-content-docs/current/general/run-a-node/advanced-topics/configuration-files.md
- [] A relating issue is created: # (<- fill the issue number here)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/683)
=> add node config

src/modules/docCatalog/index.js
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/688)
=> fix: fix home page doc link

docs/core/core-space-basics/accounts.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/689)
=> fix: change 1018 to 10^18

docs/core/core-space-basics/addresses.md
resolve #696
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/699)
=> chore: add example to contract address computation

docs/general/conflux-basics/glossary.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/702)
=> Add the defination of Encryption to the glossary 

docs/core/build/sdks-and-tools/sdks.md, docs/general/run-a-node/advanced-topics/node-configuration.md, docs/general/run-a-node/advanced-topics/running-independent-chain.md, docs/general/run-a-node/how-to-upgrad.md, docs/general/run-a-node/nodes-faqs.md, docs/general/run-a-node/run-a-node.md, yarn.lock
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/712)
=> update private node running doc

docs/espace/tutorials/upgradableContract/_category_.json, docs/espace/tutorials/upgradableContract/upgrade.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/714)
=> Add a tutorial on how to use upgradable contract on Conflux eSpace

docs/general/conflux-basics/glossary.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/723)
=> Add the definition of Keccak-256 to the glossary

docs/core/core-developer-quickstart.md, docs/core/core-space-basics/transactions/receipt.md, docs/core/tutorials/js-conflux-sdk.md, docs/core/tutorials/nft-tutorials/crc1155.md, docs/core/tutorials/nft-tutorials/crc721.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/728)
=> update js-sdk doc links, due to easy confusion with main doc site

docs/general/blockchain-security/backup-wallet.md, docs/general/blockchain-security/create-wallet.md, docs/general/tutorials/wallets/wallets.mdx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/727)
=> Add Security Advice for Wallet Backup

docs/general/build/smart-contracts/gas-optimization/erc20permit.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/730)
=> Add ERC20Permit to gas optimization

docs/general/build/smart-contracts/gas-optimization/uupsAndTransparentProxy.md
=> Add UUPS vs Transparent Proxy to gas optimization 

docs/general/hardforks/v2.4.md
=> complement hardfork v2.4 rpc change log

docs/core/core-space-basics/addresses.md
=> add details for contract address computing in core space

docs/espace/tutorials/walletConnect/nextjs.md
corrected grammatical mistake 
Context Provide to Context Provider
=> Fix grammatical mistakes in nextjs.md

docs/general/protocols/defi/uniswap-v2.md
=> Add Uniswap v2 protocol introduction 

docs/general/build/smart-contracts/gas-optimization/useVanityAddress.md
=> Add Using Vanity Address to gas optimization

docs/core/build/sdks-and-tools/tools.md, docs/espace/build/deployed-contracts.md
This PR adds the Multicall3 contract that has been deployed to the Core Space to the documentation and updates the Multicall3 contract address in the espace
close #748
close #747
=> add multicall3 contract address to document

docs/core/build/json-rpc/cfx-namespace.md, docs/espace/build/accounts.md, docs/espace/build/evm-compatibility.md
=> fix: i18n keywords indent

docs/general/conflux-basics/gas.md, docs/general/conflux-basics/spaces.md
=> remove cSpace abbreviation. Resolves #775

package.json, yarn.lock
=> bump docusaurus version to latest

docs/general/build/smart-contracts/contract-security/private-variables.md
=> Add Private Variables Security to Contract Security 

docs/espace/tutorials/upgradableContract/uups-foundry.md
=> Add Deploying Upgradeable Contracts using UUPS with Foundry

docs/espace/build/infrastructure/graph/graph.mdx
=> fix broken link

docs/templates/links.tsx
=> fixed discord link

docs/general/protocols/defi/uniswap-v3.md
=> Add Uniswap v3 protocol introduction 

docs/espace/build/infrastructure/oracles.md
=> Update oracles.md on Build/Oracles section

docs/core/core-space-basics/internal-contracts/conflux-context.md
=> Update conflux context contract

docs/general/run-a-node/advanced-topics/compiling-conflux-client.md, i18n/zh/docusaurus-plugin-content-docs/current/templates/parameters.ts
=> Update compiling conflux client on macos

docs/core/getting-started/funding-your-account.md, docs/templates/UserGuide.md
=> Add mainnet Conflux Faucets to document

docs/espace/build/infrastructure/RPC-Provider.md
=> Update eSpace RPC-Provider.md - Add Validation Cloud

docs/core/core-space-basics/accounts.md, docs/core/core-space-basics/vm-difference.md, docs/espace/build/evm-compatibility.md, docs/espace/build/jsonrpc-compatibility.md
=> update outdated content

package.json, yarn.lock
=> chore: update docusaurus version

docs/general/run-a-node/advanced-topics/node-configuration.md
=> Add content about how to build fullstate conflux binary

docs/general/conflux-basics/consensus-mechanisms/proof-of-stake/faqs.md, docs/general/conflux-basics/consensus-mechanisms/proof-of-stake/penalties_and_slash.md, docs/general/conflux-basics/consensus-mechanisms/proof-of-stake/pos_overview.md, docs/general/mine-stake/stake/stake.mdx
=> add pos slashing doc

docs/templates/parameters.ts
=> update conflux node version

docs/general/conflux-basics/wallets.md
=> Update wallets.md: fix typo

docs/general/conflux-basics/consensus-mechanisms/proof-of-stake/penalties_and_slash.md, docs/general/mine-stake/stake/stake.mdx
=> update the doc of pos stake

.github/workflows/test-l10n_deploy.yaml
=> Update l10n ci node versioin

docs/espace/DeveloperQuickstart.md
=> Remove forge create optional parameter --legacy

docs/general/conflux-basics/consensus-mechanisms/proof-of-stake/penalties_and_slash.md, docs/general/mine-stake/stake/safe-node-restart.md, docs/general/run-a-node/how-to-upgrad.md
=> Highlight safe node restart. Resolves #858

plugins/docusaurus-openrpc/package.json, plugins/docusaurus-openrpc/src/components/Content/index.css, plugins/docusaurus-openrpc/src/components/Content/index.tsx, plugins/docusaurus-openrpc/src/components/Playground/index.tsx, plugins/docusaurus-openrpc/src/components/Theme/index.tsx, yarn.lock
This PR fix dark mode color.
resolve #865
=> chore: fix dark mode color

README.md, docs/core/core-developer-quickstart.md, docs/core/core-endpoints.md, docs/core/core-space-basics/addresses.md, docs/core/core-space-basics/internal-contracts/params-control.md, docs/core/core-space-basics/sponsor-mechanism.md, docs/core/core-space-basics/transactions/why-transaction-is-pending.md, docs/core/getting-started/funding-your-account.md, docs/core/tutorials/how-to-sponsor-contract.md, docs/core/tutorials/nft-tutorials/crc1155.md, docs/core/tutorials/nft-tutorials/crc721.md, docs/espace/DeveloperQuickstart.md, docs/espace/Overview.md, docs/espace/UserGuide.md, docs/espace/network-endpoints.md, docs/espace/tutorials/VerifyContracts.md, docs/espace/tutorials/deployContract/brownie.md, docs/general/CONTRIBUTING/contributor-poaps.md, docs/general/article-collection-links/reference-links.md, docs/general/conflux-basics/accounts.md, docs/general/conflux-basics/glossary.md, docs/general/faq/community-faqs.md, docs/general/mine-stake/stake/become-a-solo-validator.md, docs/general/tutorials/transferring-funds/across-chains/_transfer-funds-across-chains-multichain.md, docs/general/tutorials/wallets/ledger.md, sidebars.js
=> replace scan link

docs/core/build/json-rpc/cfx-namespace.md
=> Mark cfx_depositList as deprecated

docs/core/build/gas-sponsorship.md, docs/core/build/quickstart-for-eth-devs.md, docs/core/build/sdks-and-tools/tools.md, docs/espace/build/cross-space-bridge.md, docs/espace/build/infrastructure/RPC-Provider.md, docs/espace/build/infrastructure/confluxscan-api.md, docs/general/build/tools/web3paywall.md
This PR updates the Conflux Scan URL
=> chore: update scan url

docs/core/build/json-rpc/cfx-namespace.md
resolve #884 
resolve #882
resolve #883
=> chore: fix rpc method params

docs/core/tutorials/_category_.yml, docs/espace/build/sdks/_category_.json, docs/espace/tutorials/sdks/_category_.json, docs/general/article-collection-links/_category_.yml, docs/general/blockchain-security/_category_.yml, docs/general/protocols/_category_.yml
=> chore: update category collapsed state to true for various sections

plugins/docusaurus-openrpc/src/components/JSONSchemaViewer/utils/detectTypes.ts
=> chore: fix typo in comment

docs/general/run-a-node/advanced-topics/compiling-conflux-client.md
=> Update conflux-rust compile dependencies version

docs/general/mine-stake/stake/staking-overview.mdx
=> remove broken links

package.json, yarn.lock
=> Upgrade docusaurus

docs/espace/tutorials/scaffoldCfx/scaffold2.md
remove redundant word in scaffold2.md
=> chore: remove redundant word in scaffold2.md

docs/general/hardforks/v3.0.md
=> V3.0.0 mainnet

docs/general/conflux-basics/ecosystem.md, docs/general/mine-stake/stake/pos-pools-list.md
- [x ] I have read the [Contributing Guidelines on pull requests](https://doc.confluxnetwork.org/docs/general/CONTRIBUTING#create-a-pull-request).
- [929] A relating issue is created: # (<- fill the issue number here)
- [x ] **This is NOT a PR to submit translation**
=> edited conflux-pos-validators link in 2 places, it doesn't have a redirect for www

docs/core/core-space-basics/transactions/lifecycle.md, docs/core/core-space-basics/transactions/nonce.md
=> chore: fix some typos in docs
