docs/general/build/smart-contracts/gas-optimization/constant.md, docs/general/build/smart-contracts/gas-optimization/gas-optimization.md, docs/general/build/smart-contracts/introduction-to-smart-contracts.md, docs/general/conflux-basics/gas.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/453)
=> update general/conflux-basics/gas.md, regarding the issue #451

docs/general/CONTRIBUTING/reward-guidelines.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/508)
=> regular review of reward guideline

docs/general/build/smart-contracts/gas-optimization/sstore2.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/573)
=> Refs #454 -- Added SSTORE2 to general/build/smart-contracts/gas-optimization 

docs/general/build/smart-contracts/contract-security/mixed-accounting.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/574)
=> Refs #474 -- Added MixedAccounting to general/build/smart-contracts/contract-security

docs/general/build/smart-contracts/gas-optimization/timestamps-and-blocknumbers.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/588)
=> Refs #454 -- Added timestamps-and-blocknumbers to general/build/smart-contracts/gas-optimization

docs/general/build/smart-contracts/gas-optimization/storage-pointer.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/591)
=> Refs #454 -- Added Storage Pointer to general/build/smart-contracts/gas-optimization 

docs/general/build/smart-contracts/gas-optimization/self-destruct.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/602)
=> Refs #454 -- Added SelfDestruct to general/build/smart-contracts/gas-optimization 

docs/general/build/smart-contracts/gas-optimization/monolithic-architecture.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/620)
=> Refs #454 -- Added monolithic-architecture.md to general/build/smart-contracts/gas-optimization 

docs/general/build/smart-contracts/gas-optimization/multicall-in-router.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/619)
=> Refs #454 -- Added multicall-in-router.md to general/build/smart-contracts/gas-optimization 

docs/espace/tutorials/VerifyContracts.md
Location: /docs/espace/tutorials/VerifyContracts
https://doc.confluxnetwork.org/docs/espace/tutorials/VerifyContracts
eSpace Testnet url for the network configuration on Hardhat guide is incorrect.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/679)
=> Fix eSpace Testnet url  VerifyContracts.md

docs/espace/tutorials/digitalSignature/ECDSA.md, docs/espace/tutorials/digitalSignature/_category_.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/680)
=> Add a tutorial on how to use ECDSA Signature

docs/espace/tutorials/upgradableContract/transparent-proxy.md
=> Add tutorial for deploying upgradeable contracts using transparent proxy

docs/general/protocols/_category_.yml, docs/general/protocols/defi/_category_.yml, docs/general/protocols/defi/uniswap-v1.md, docs/general/protocols/defi/uniswap.md
=> Add Uniswap v1 protocol introduction

docs/general/build/smart-contracts/gas-optimization/oz-alternatives.md
=> Add Alternatives to OpenZeppelin to gas optimization 

docs/espace/tutorials/upgradableContract/upgrade-foundry.md
=> Add Deploying Upgradeable Contracts using Foundry

docs/general/run-a-node/advanced-topics/node-configuration.md, docs/general/run-a-node/nodes-faqs.md
=> update running node doc

docs/general/build/smart-contracts/gas-optimization/assemblyMathOperations.md
=> Add Using Assembly for Math Operations

docs/general/build/smart-contracts/gas-optimization/useSUBorXOR.md
=> Add Using SUB or XOR Instead of ISZERO(EQ)

docs/core/core-endpoints.md, docs/general/hardforks/v2.0.md, plugins/docusaurus-openrpc/src/components/JSONSchemaViewer/components/index.ts
=> chore: fix some typos

docusaurus.config.js
As requested by @0xn1c0,  I  enabled the search widget for the CDP, the simplest way was to leverage Algolia search widget already integrated with Docusaurus.
Here a deployed example can be found: https://conflux-documentation-phi.vercel.app/
Code-Wise, only a few lines are needed in the docusaurus.config.js, but to integrate with Algolia multiple steps need to be done on their website to create the configuration and index the data.
these 4 values need to be filled in to work properly:
ALGOLIA_VERIFY
ALGOLIA_APP_ID
ALGOLIA_API_KEY
ALGOLIA_INDEX_NAME
These value can either be set as env vars or set in the defaulting value in the docusaurus.config.js itself 
Algolia offer a wizard to confgure a new application:
- is important to select DocSearch as search plan
- the domain should match the …
=> Update docusaurus.config.js to enable algolia search widget
